### ISSUE TITLE
[PCM-examples] Can't compile

### ISSUE THREAD

**Issue by kdungs** [betatim/NeedForSpeed#6]
With only the information given in the README, I am not able to compile.

I downloaded the IntelPerformanceCounterMonitorV2.6 from the official website and set the $PCMSDK path accordingly. Now when I run make (in either $PCMSDK or the PCM folder of this project), I get an error saying

```
In file included from msr.cpp:25:0:
msr.h:30:25: fatal error: MSRAccessor.h: No such file or directory
 #include <MSRAccessor.h>
```

I know this isn't strictly an issue with this project, but since you got it to run on your machine, maybe you can tell what someone has to do in order to get it running.

**Comment by kdungs** [comment]
Okay, this is actually specified in PCM's README:

```
Automatic Install
-----------------
In the MacMSRDriver directory run 'make install', which will build both the driver and dynamic library for accessing the driver.
It loads the driver, installs the library into /usr/lib and installs the library headers into /usr/include.

Manual Install
--------------
The driver and library can be built individually and without being installed using 'make kext' and 'make library' respectively.
Once built, they are located in MacMSRDriver/build/Release. They can also be built by opening the PcmMsr project with xcode and building
both projects.

Then do the following:
    1) load the driver by running kextload.sh
    2) copy libPcmMsr.dylib to a location on your path (auto-install uses /usr/lib)
    3) copy MSRKernel.h to a location on your path (auto-install uses /usr/include)
    4) copy MSRAccessorPublic.h as MSRAccessor.h to a location on your path (auto-install uses /usr/include)
```

So on a Mac, one has to go to the $PCMSDK directory and run `sudo make install` (running `make install` w/o `sudo` will prompt for password, so that works as well) and then everything works nice and fine.
